### ISSUE TITLE
QA feedback 26/12 - Visualization interface

### ISSUE THREAD

**Issue by quentinberder** [csviz/csviz#33]
![feedback_1](https://cloud.githubusercontent.com/assets/561834/5555268/b610b3d2-8ce0-11e4-959e-632696295028.png)

- [x] **Red** - Borders are not consistent.
- [x] **Blue** - No logo displayed
- [x] **Green** - Buttons are not well designed, the borders are difficult to see.
- [x] **Clear blue** - Design of the average is different.

Question:

* ~~What do you think of having a collapsing menu?~~

![feedback_2](https://cloud.githubusercontent.com/assets/561834/5555284/67c6e006-8ce1-11e4-9646-c1a4ef1a205a.png)

- [x] The menu is not styled.
- [x] We should add a quick search as for the country list.

![feedback_3](https://cloud.githubusercontent.com/assets/561834/5555289/cc5f1d08-8ce1-11e4-9f60-4df73bf82941.png)

- [x] Displays no data, it has however data for 2009 and 2011.

**Comment by quentinberder** [comment]
@fraserxu @xeodou we should have this open a modal with the information that would be coming from the edit page.

**Comment by fraserxu** [comment]
I added the about modal, need the content of it somehow from the config. 

@xeodou I guess you can have a text field somewhere in the config so the user could add it from the edit page, I'll use it in the front end.

**Comment by xeodou** [comment]
I can working on this.

**Comment by quentinberder** [comment]
Closing.
