### ISSUE TITLE
QA 06

### ISSUE THREAD

**Issue by quentinberder** [csviz/csviz#36]
A few feedbacks:

- [ ] When clicking the arrow button on the search box on the dropdown list of the countries, it is not closing the list.
- [x] <del>Clicking the country is not updating the table on the right. It should center on the selected country. The best being having the country pushed to the top</del>
- [x] <del>Can we have the multiple countries select on top of it?</del>
- [x] CSS issue when clicking the play button.
- [x] It seems the top of the bubble is cut
![temp4](https://cloud.githubusercontent.com/assets/561834/5623477/bbadc61a-958f-11e4-8d01-b01715acf67e.png)
- [x] <del>Need to highlight the year in the right menu.</del>
- [x] For long indicator names, it is cut.

![temp5](https://cloud.githubusercontent.com/assets/561834/5623480/d0babcac-958f-11e4-8f2b-a1ec15a93dca.png)

- [x] Legend is impossible to read with this design.

/cc @fraserxu @z4rd

**Comment by quentinberder** [comment]
> No. We have already discussed about it. It's not feasible in the current code base. The logic is design to have only one active country at a time.

Ok I get it. How long do you estimate it would lake to implement it (I presume for a latter phase)?

> I'm not sure about the last issue because when you click the country from the sidebar table, it will flick to the top, which is not what the user may expect.

Indeed that is a good point.

**Comment by fraserxu** [comment]
> Need to highlight the year in the right menu.

The menu(scatter plot) will open if it's the selected country and has data.

> For long indicator names, it is cut.
> Legend is impossible to read with this design.

Will wait for @z4rd when she has time.

> CSS issue when clicking the play button.
> It seems the top of the bubble is cut 

Fixed.

**Comment by z4rd** [comment]
> Legend is impossible to read with this design.

You mean the tablet one or the desktop one? @quentinberder

**Comment by quentinberder** [comment]
> You mean the tablet one or the desktop one? @quentinberder

Desktop.

**Comment by quentinberder** [comment]
Closing.
