### ISSUE TITLE
CSS issues

### ISSUE THREAD

**Issue by hunvreus** [csviz/csviz#42]
A few things we need to fix:

- On mobile, the list of countries is broken (weird space on the side). I tried to fix it yesterday but it doesn't seem to work.

    ![map3](https://cloud.githubusercontent.com/assets/306868/5914540/62509f9e-a632-11e4-8350-52777ba01463.png)

- Collapse/expand is hovering on top of the sidebar. I actually think you should convert it back to the thing you had before (always display it next to the sidebar). Also use a much thinner block, and use left and right arrows for the icon, with a black, semi-transparent background (same as the legend).

    ![map2](https://cloud.githubusercontent.com/assets/306868/5914541/627b0720-a632-11e4-88ec-2b3b63fcda7e.png)

- Move the legend to the left above the timeline.

    ![map](https://cloud.githubusercontent.com/assets/306868/5914542/628fc2a0-a632-11e4-8ed0-38363957fd17.png)

Please test mobile every time you make changes.

**Comment by z4rd** [comment]
> - Move the legend to the left above the timeline.
Some of the sidebar options don't have the timeline,
the margin of the legend will be weird @hunvreus

**Comment by hunvreus** [comment]
Then switch the two, timeline and legend.

**Comment by z4rd** [comment]
> - Then switch the two, timeline and legend.

The height of the lengend is uncertain, when the fragile states checked:
- [x] Fragile States

**Comment by quentinberder** [comment]
Done, closing.
