### ISSUE TITLE
Deleting indicator

### ISSUE THREAD

**Issue by quentinberder** [csviz/csviz#43]
We use to have a way to delete the indicator through the interface. Add a remove button in the indicator section.

**Comment by xeodou** [comment]
![image](https://cloud.githubusercontent.com/assets/914595/6425016/aa0619c4-bf4e-11e4-8cea-776938f34f19.png)
Is it good ?

**Comment by quentinberder** [comment]
Perfect. You can close if pushed and tested.

**Comment by xeodou** [comment]
Sure. I have already pushed and tested.
